# Generated by Django 3.1 on 2020-11-15 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('context', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(choices=[('SL', 'Select Event'), ('Mosaic', 'Mosaic'), ('Spybits', 'Spybits'), ('Digisim', 'Digisim'), ('Continuum', 'Continuum'), ('Cassandra', 'Cassandra'), ('Commnet', 'Commnet'), ('Funckit', 'Funckit'), ('X-IoT-A', 'X-IoT-A'), ('I-Chip', 'I-Chip')], default='SL', max_length=20)),
                ('members_from_1st_year', models.IntegerField()),
                ('members_after_1st_year', models.IntegerField()),
                ('score', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('url', models.URLField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='udyam_backend.event')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_members', models.CharField(choices=[('SL', 'Select No. of Members'), ('1', '1'), ('2', '2'), ('3,', '3')], default='SL', max_length=2)),
                ('team_name', models.CharField(max_length=50)),
                ('Team_leader', models.EmailField(blank=True, max_length=254)),
                ('member1', models.EmailField(blank=True, max_length=254)),
                ('member2', models.EmailField(blank=True, max_length=254)),
                ('member3', models.EmailField(blank=True, max_length=254)),
                ('team_score', models.IntegerField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='udyam_backend.event')),
            ],
        ),
    ]
