# Generated by Django 3.1 on 2021-01-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udyam_backend', '0002_broadcast_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='group_link',
            field=models.CharField(default='xyz', max_length=100),
            preserve_default=False,
        ),
    ]
