# Generated by Django 3.1 on 2021-01-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udyam_backend', '0003_event_group_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='number_of_members',
            field=models.CharField(choices=[('SL', 'Select No. of Members'), ('1', '1'), ('2', '2'), ('3', '3')], default='SL', max_length=2),
        ),
    ]
