# Generated by Django 3.1 on 2021-01-20 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('udyam_backend', '0004_auto_20210112_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='udyam_backend.event')),
            ],
        ),
    ]
