# Generated by Django 3.1 on 2021-03-30 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udyam_backend', '0005_team_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team_list',
            options={'verbose_name': 'Team List', 'verbose_name_plural': 'Team List'},
        ),
    ]
