# Generated by Django 3.1 on 2021-04-11 11:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('udyam_backend', '0006_auto_20210331_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Personal Email to all Members',
                'verbose_name_plural': 'Personal Email',
            },
        ),
    ]
